# {{ $DefaultTitle := "Bump upstream CRD version" }}

name: '{{ default $DefaultTitle .title }}'

# {{ if .pipelineid }}
pipelineid: '{{ .pipelineid }}'
# {{ end }}

scms:
  default:
    kind: github
    spec:
      owner: {{ .scm.owner }}
      repository: {{ .scm.repository }}
      username: {{ .scm.username }}
      branch: {{ .scm.branch }}

sources:
  # Verify that the upstream Github Release calculated by `git-tag-replay` action truly exists
  upstream:
    kind: githubrelease
    spec:
      owner: {{ .upstream.owner }}
      repository: {{ .upstream.repository }}
      versionfilter:
        kind: semver
#{{ if .upstream.next_version }}
        pattern: {{ .upstream.next_version }}
#{{ else }}
        pattern: {{ requiredEnv .upstream.env_version }}
#{{ end }}
    transformers:
      - trimprefix: "v"

targets:
  apply-to-projen:
    # `apply-to-projen` will only execute when source#upstream actually exists
    name: "Update CRD version in .projenrc.json"
    kind: json
    sourceid: upstream
    scmid: default
    spec:
      engine: "dasel/v2"
      file: ".projenrc.json"
      key: "latestVersionOnBranch"
  regenerate-workflows-and-sdks:
    # `regenerate-workflows-and-sdks` will only execute when target#apply-to-projen actually changed `.projenrc.json`
    name: "Regenerate SDKs"
    dependson: ["target#apply-to-projen"]
    dependsonchange: true
    kind: shell
    scmid: default
    disablesourceinput: true
    spec:
      command: |
        mise trust
        npm install
        npx projen
        make clean build

actions:
  default:
    # The action title is used to define the pullrequest title
    # Since we use the groupby set to all we need to be sure that the pullrequest title
    # is the same for all the pipeline generated by autodiscovery.
    title: Bump upstream CRD version
    kind: github/pullrequest
    scmid: default
    spec:
      labels:
        - "dependencies"
